### PR TITLE
Test Netlify preview builds

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
https://5cefdd285a167d00088da20d--admiring-ride-e270b5.netlify.com/docs/en/next/installation.html

**Comment by juanpicado** [comment]
😱😱😱I dreamed with this for so long

**Comment by juanpicado** [comment]
But how this is automated ?

**Comment by DanielRuf** [comment]
We just have to add Netlify to the repository (give it access through its setup page) and change the settings to our needs.

image

**Pull request closed without merging**
